import Head from "next/head";
import styles from "../styles/Home.module.css";
import client from "../lib/contentfulService";
import {Header} from "../components/Header/Header";
import {IHeaderData } from "../types/types";

const Home = ({headerData}: { headerData: IHeaderData}) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header {...headerData}/>
        </div>
    );
};
export const getStaticProps = async () => {
    const { items } = await client.getEntries();
    const field =  (items[0].fields as IHeaderData);
    const headerData =  {
        ttile: field.ttile,
        searchLabel: field.searchLabel,
        menuLabel: field.menuLabel,
        logo: {
        url: field.logo.fields?.file.url,
            title: field.logo.fields?.title
        },
    }
    return {
        props: {
            headerData,
        }
    }
}

export default Home;
